spring.application.name=sms-service
server.port = 8082
spring.datasource.url=jdbc:postgresql://localhost:5432/sms_db
spring.datasource.username=swapnilbagate
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update